name: Flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E741,E743,E121,E123,E126,E226,E24,E704,W503,W504"
          max-line-length: "128"
